function bisection_t = loadBisectionStruct()
    bisection_t = struct('s', [], 'sim', [], 'H', [], ...
        'dstar', [], 'f', [], 'tigt_gap', [], 'gap', [], ...
        'sum_cost', [], 'signed_cost', [], 'sum_signed_cost', [], ...
        'centroid_t', []);
end